apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
  namespace: microwave
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://notifications-db:5432/notifications_db
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
