apiVersion: v1
kind: Secret
metadata:
  name: notifications-credentials
  namespace: microwave
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: notifications
  SPRING_DATASOURCE_PASSWORD: notifications
