apiVersion: v1
kind: Service
metadata:
  name: notifications
  namespace: microwave
spec:
  type: NodePort
  selector:
    app: notifications
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30085
