server:
  port: 8082

spring:
  application:
    name: payments
  datasource:
    url: jdbc:postgresql://localhost:5432/payments_db
    username: payments
    password: payments
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health
