apiVersion: v1
kind: Secret
metadata:
  name: notifications-db-credentials
  namespace: microwave
type: Opaque
stringData:
  POSTGRES_DB: notifications_db
  POSTGRES_USER: notifications
  POSTGRES_PASSWORD: notifications
