apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  namespace: microwave
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://orders-db:5432/orders_db
  CATALOG_SERVICE_URL: http://catalog:8081
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
