server:
  port: 8083

spring:
  application:
    name: orders
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: orders
    password: orders
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

catalog:
  service:
    url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health
